
resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:stevewallecs/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - get: pcf-pipelines
  - task: deploy
    file: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task-test.yml
