---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task-test.sh
